version: "3"
services:
  influxdb:
    container_name: unpoller-influxdb
    restart: unless-stopped
    image: influxdb:1.8
    ports:
      - '8085:8086'
      - '8088:8088'
    volumes:
      - /root/unpoller/influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=unifi
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=CHANGE_ME
  unpoller:
    container_name: unpoller-app
    restart: unless-stopped
    image: golift/unifi-poller:latest
    depends_on:
      - influxdb
    volumes:
      - /root/unpoller:/config
